export const CATEGORIAS = [
  'Ilustração digital',
  'Fanart',
  'Animação',
  'Pixel art',
  'Concept art',
  'Pintura',
  'Retrato',
  'Wallpaper',
  'Background',
  'Foto de perfil',
  'Banner',
  'Webtoon',
  'Painel de mangá',
  'Capa de mangá',
  'Tirinha',
  'Character sheet',
  'Full body',
  'Half body',
  'Pose',
  'Design de roupa',
  'Design de monstros',
  'Cenário de jogo',
  'Cenário de animação',
  'Cityscape',
  'Gif animado',
  'Loop animation',
  'Fan animation',
  'Sticker',
  'PNGtuber',
  'Tela de loading',
  'Overlay de stream',
  'Assets 2D',
  'Splash art',
  'Item art',
  'Texturas',
  'Surrealismo',
  'Desenho vetorial',
  'Cell shading',
  'Minimalista',
  'OC',
  'Doodle',
  'Line art',
  'Sketch',
];

export const ESTILOS = [
  'Mangá',
  'Cartoon',
  'Realista',
  'Semi realista',
  'Chibi',
  'Kawaii',
  'Cute',
  'Gótico',
  'Dark',
  'Horror',
  'Gothic horror',
  'Fantasia',
  'Sci-fi',
  'Cyberpunk',
  'Furry',
  'Kemonomimi',
  'Moe',
  'Super deformed',
  'Y2K',
  'Pop art',
  'Noir',
  'Vintage',
  'Grunge',
  'Punk',
  'Vaporwave',
  'Synthwave',
  'Retrô',
  'Flat color',
  'Arte vetorial',
  'Graffiti',
  'Impressionista',
  'Expressionista',
  'Psicodélico',
  'Dark fantasy',
  'Art nouveau',
  'Weirdcore',
  'Lineless',
  'Sketchy',
  'Low poly',
  'Cottagecore',
  'Watercolor',
  'Fairycore',
  'Renderização rústica',
  'Soft shading',
  'Hiper-realista',
  'Gouache',
  'Voxel art',
  'Dreamcore',
];
